# Loading and Preprocessing data with tf

Often we want to use datasets that do not fit in RAM, or it is at least very cumbersome. TF has some API's that can assist with working with large datasets.

The Data API can handle data from csv, binaries and SQL-databases.


There are several ways of handling categorical featues, such as one-hot encoding (dummy variables), bag-of-words encoding or _embeddings_ <- (This must be explored)

In [1]:
import tensorflow as tf
from tensorflow import keras

In [2]:
X = tf.range(10)

In [10]:
dataset = tf.data.Dataset.from_tensor_slices(X)

In [6]:
dataset

<TensorSliceDataset shapes: (), types: tf.int32>

In [7]:
for item in dataset:
    print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)


In [11]:
dataset = dataset.repeat(3).batch(7,drop_remainder = True)
for item in dataset:
    print(item)

tf.Tensor([0 1 2 3 4 5 6], shape=(7,), dtype=int32)
tf.Tensor([7 8 9 0 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([4 5 6 7 8 9 0], shape=(7,), dtype=int32)
tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int32)


In [12]:
dataset = dataset.map(lambda x : x*2)

In [15]:
for item in dataset:
    print(item)

tf.Tensor([ 0  2  4  6  8 10 12], shape=(7,), dtype=int32)
tf.Tensor([14 16 18  0  2  4  6], shape=(7,), dtype=int32)
tf.Tensor([ 8 10 12 14 16 18  0], shape=(7,), dtype=int32)
tf.Tensor([ 2  4  6  8 10 12 14], shape=(7,), dtype=int32)
